"""phase-1 kernel schema

Revision ID: e01e50e0d577
Revises:
Create Date: 2026-09-02 22:52:59.772949
"""

from __future__ import annotations

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision = "e01e50e0d577"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("state_version", sa.Integer(), nullable=False),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("type", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("account", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_account_code"), ["code"], unique=True)

    op.create_table(
        "api_token",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
        sa.Column("token_hash", sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
        sa.Column("subject", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
        sa.Column("kind", sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
        sa.Column("scopes", sa.JSON(), nullable=True),
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("revoked_at", sa.DateTime(), nullable=True),
        sa.Column("revoked_reason", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("last_used_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("api_token", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_api_token_subject"), ["subject"], unique=False)
        batch_op.create_index(batch_op.f("ix_api_token_token_hash"), ["token_hash"], unique=True)

    op.create_table(
        "approval_request",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("state_version", sa.Integer(), nullable=False),
        sa.Column("document_type", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column("document_id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
        sa.Column("document_number", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=True),
        sa.Column("tool_name", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("requested_by", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
        sa.Column("reason", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("projected_effects_json", sa.JSON(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column("decided_by", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
        sa.Column("decided_at", sa.DateTime(), nullable=True),
        sa.Column("decision_comment", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("approval_request", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_approval_request_document_id"), ["document_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_approval_request_document_type"), ["document_type"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_approval_request_status"), ["status"], unique=False)

    op.create_table(
        "customer",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("state_version", sa.Integer(), nullable=False),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("credit_limit_cents", sa.Integer(), nullable=False),
        sa.Column("payment_terms_days", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("customer", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_customer_code"), ["code"], unique=True)

    op.create_table(
        "document_sequence",
        sa.Column("prefix", sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
        sa.Column("next_value", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("prefix"),
    )
    op.create_table(
        "event",
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("type", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("document_type", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
        sa.Column("document_id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=True),
        sa.Column("receipt_id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=True),
        sa.Column("actor_id", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
        sa.Column("payload_json", sa.JSON(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("seq"),
    )
    with op.batch_alter_table("event", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_event_document_id"), ["document_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_event_type"), ["type"], unique=False)

    op.create_table(
        "fiscal_period",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("state_version", sa.Integer(), nullable=False),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(length=7), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("fiscal_period", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_fiscal_period_code"), ["code"], unique=True)

    op.create_table(
        "idempotency_record",
        sa.Column("key", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
        sa.Column("tool_name", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("request_hash", sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
        sa.Column("response_json", sa.JSON(), nullable=True),
        sa.Column("receipt_id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "item",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("state_version", sa.Integer(), nullable=False),
        sa.Column("sku", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("standard_cost_cents", sa.Integer(), nullable=False),
        sa.Column("list_price_cents", sa.Integer(), nullable=False),
        sa.Column("is_stocked", sa.Boolean(), nullable=False),
        sa.Column("on_hand_qty", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("item", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_item_sku"), ["sku"], unique=True)

    op.create_table(
        "open_item",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("state_version", sa.Integer(), nullable=False),
        sa.Column("kind", sqlmodel.sql.sqltypes.AutoString(length=2), nullable=False),
        sa.Column("party_id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
        sa.Column("source_doc_type", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column("source_doc_id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
        sa.Column("source_doc_number", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column("amount_cents", sa.Integer(), nullable=False),
        sa.Column("remaining_cents", sa.Integer(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("open_item", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_open_item_kind"), ["kind"], unique=False)
        batch_op.create_index(batch_op.f("ix_open_item_party_id"), ["party_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_open_item_source_doc_id"), ["source_doc_id"], unique=False
        )

    op.create_table(
        "policy_version",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("yaml_text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("policy_hash", sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
        sa.Column("comment", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("updated_by", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("policy_version", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_policy_version_version"), ["version"], unique=False)

    op.create_table(
        "receipt",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
        sa.Column("tool_name", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("actor_id", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
        sa.Column("actor_kind", sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
        sa.Column("on_behalf_of", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
        sa.Column("document_type", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
        sa.Column("document_id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=True),
        sa.Column("document_number", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=True),
        sa.Column("before_hash", sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
        sa.Column("action_hash", sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
        sa.Column("after_hash", sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
        sa.Column("signature", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("public_key_id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
        sa.Column("signed_at", sa.DateTime(), nullable=False),
        sa.Column("idempotency_key", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
        sa.Column("payload_json", sa.JSON(), nullable=True),
        sa.Column("projection_json", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("receipt", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_receipt_actor_id"), ["actor_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_receipt_document_id"), ["document_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_receipt_tool_name"), ["tool_name"], unique=False)

    op.create_table(
        "server_key",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
        sa.Column("public_key_pem", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("private_key_pem", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("retired_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "supplier",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("state_version", sa.Integer(), nullable=False),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("payment_terms_days", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("supplier", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_supplier_code"), ["code"], unique=True)

    op.create_table(
        "journal_entry",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("state_version", sa.Integer(), nullable=False),
        sa.Column("number", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column("period_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("period_code", sqlmodel.sql.sqltypes.AutoString(length=7), nullable=False),
        sa.Column("posting_date", sa.Date(), nullable=False),
        sa.Column("memo", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("source_type", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column("source_id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
        sa.Column("reversal_of_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
        sa.Column("total_debit_cents", sa.Integer(), nullable=False),
        sa.Column("receipt_id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=True),
        sa.ForeignKeyConstraint(
            ["period_id"],
            ["fiscal_period.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reversal_of_id"],
            ["journal_entry.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("journal_entry", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_journal_entry_number"), ["number"], unique=True)
        batch_op.create_index(
            batch_op.f("ix_journal_entry_period_code"), ["period_code"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_journal_entry_period_id"), ["period_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_journal_entry_source_id"), ["source_id"], unique=False)

    op.create_table(
        "purchase_order",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("state_version", sa.Integer(), nullable=False),
        sa.Column("number", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column("supplier_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("total_cents", sa.Integer(), nullable=False),
        sa.Column("memo", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
        sa.Column("approved_by", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
        sa.Column("approved_at", sa.DateTime(), nullable=True),
        sa.Column("cancelled_reason", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["supplier.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("purchase_order", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_purchase_order_number"), ["number"], unique=True)
        batch_op.create_index(batch_op.f("ix_purchase_order_status"), ["status"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_purchase_order_supplier_id"), ["supplier_id"], unique=False
        )

    op.create_table(
        "sales_order",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("state_version", sa.Integer(), nullable=False),
        sa.Column("number", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column("customer_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("total_cents", sa.Integer(), nullable=False),
        sa.Column("memo", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
        sa.Column("cancelled_reason", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customer.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sales_order", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_sales_order_customer_id"), ["customer_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_sales_order_number"), ["number"], unique=True)
        batch_op.create_index(batch_op.f("ix_sales_order_status"), ["status"], unique=False)

    op.create_table(
        "customer_invoice",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("state_version", sa.Integer(), nullable=False),
        sa.Column("number", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column("customer_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("so_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("shipment_ids", sa.JSON(), nullable=True),
        sa.Column("lines", sa.JSON(), nullable=True),
        sa.Column("total_cents", sa.Integer(), nullable=False),
        sa.Column("credited_cents", sa.Integer(), nullable=False),
        sa.Column("posting_date", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
        sa.Column("due_date", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
        sa.Column("journal_entry_id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=True),
        sa.Column("open_item_id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customer.id"],
        ),
        sa.ForeignKeyConstraint(
            ["so_id"],
            ["sales_order.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("customer_invoice", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_customer_invoice_customer_id"), ["customer_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_customer_invoice_number"), ["number"], unique=True)
        batch_op.create_index(batch_op.f("ix_customer_invoice_so_id"), ["so_id"], unique=False)

    op.create_table(
        "goods_receipt",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("state_version", sa.Integer(), nullable=False),
        sa.Column("number", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column("po_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("received_at", sa.DateTime(), nullable=False),
        sa.Column("lines", sa.JSON(), nullable=True),
        sa.Column("journal_entry_id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=True),
        sa.Column("total_cents", sa.Integer(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column("reversal_of_id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=True),
        sa.Column("invoiced_qty_total", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["po_id"],
            ["purchase_order.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("goods_receipt", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_goods_receipt_number"), ["number"], unique=True)
        batch_op.create_index(batch_op.f("ix_goods_receipt_po_id"), ["po_id"], unique=False)

    op.create_table(
        "journal_line",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("state_version", sa.Integer(), nullable=False),
        sa.Column("entry_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("line_no", sa.Integer(), nullable=False),
        sa.Column("account_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("account_code", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column("debit_cents", sa.Integer(), nullable=False),
        sa.Column("credit_cents", sa.Integer(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["account.id"],
        ),
        sa.ForeignKeyConstraint(
            ["entry_id"],
            ["journal_entry.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("journal_line", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_journal_line_account_code"), ["account_code"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_journal_line_account_id"), ["account_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_journal_line_entry_id"), ["entry_id"], unique=False)

    op.create_table(
        "purchase_order_line",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("state_version", sa.Integer(), nullable=False),
        sa.Column("po_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("line_no", sa.Integer(), nullable=False),
        sa.Column("item_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("sku", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("qty", sa.Integer(), nullable=False),
        sa.Column("unit_cost_cents", sa.Integer(), nullable=False),
        sa.Column("received_qty", sa.Integer(), nullable=False),
        sa.Column("invoiced_qty", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["item.id"],
        ),
        sa.ForeignKeyConstraint(
            ["po_id"],
            ["purchase_order.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("purchase_order_line", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_purchase_order_line_po_id"), ["po_id"], unique=False)

    op.create_table(
        "sales_order_line",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("state_version", sa.Integer(), nullable=False),
        sa.Column("so_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("line_no", sa.Integer(), nullable=False),
        sa.Column("item_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("sku", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("qty", sa.Integer(), nullable=False),
        sa.Column("unit_price_cents", sa.Integer(), nullable=False),
        sa.Column("shipped_qty", sa.Integer(), nullable=False),
        sa.Column("invoiced_qty", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["item.id"],
        ),
        sa.ForeignKeyConstraint(
            ["so_id"],
            ["sales_order.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sales_order_line", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sales_order_line_so_id"), ["so_id"], unique=False)

    op.create_table(
        "shipment",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("state_version", sa.Integer(), nullable=False),
        sa.Column("number", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column("so_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("shipped_at", sa.DateTime(), nullable=False),
        sa.Column("lines", sa.JSON(), nullable=True),
        sa.Column("journal_entry_id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=True),
        sa.Column("cogs_cents", sa.Integer(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column("reversal_of_id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=True),
        sa.Column("invoiced_qty_total", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["so_id"],
            ["sales_order.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("shipment", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_shipment_number"), ["number"], unique=True)
        batch_op.create_index(batch_op.f("ix_shipment_so_id"), ["so_id"], unique=False)

    op.create_table(
        "supplier_invoice",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("state_version", sa.Integer(), nullable=False),
        sa.Column("number", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column("supplier_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("po_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("grn_ids", sa.JSON(), nullable=True),
        sa.Column("supplier_reference", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("lines", sa.JSON(), nullable=True),
        sa.Column("total_cents", sa.Integer(), nullable=False),
        sa.Column("variance_cents", sa.Integer(), nullable=False),
        sa.Column("match_status", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column("posting_date", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
        sa.Column("journal_entry_id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=True),
        sa.Column("open_item_id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.ForeignKeyConstraint(
            ["po_id"],
            ["purchase_order.id"],
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["supplier.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("supplier_invoice", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_supplier_invoice_number"), ["number"], unique=True)
        batch_op.create_index(batch_op.f("ix_supplier_invoice_po_id"), ["po_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_supplier_invoice_supplier_id"), ["supplier_id"], unique=False
        )

    op.create_table(
        "credit_note",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("state_version", sa.Integer(), nullable=False),
        sa.Column("number", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column("customer_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("invoice_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("amount_cents", sa.Integer(), nullable=False),
        sa.Column("reason", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("posting_date", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
        sa.Column("journal_entry_id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=True),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customer.id"],
        ),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["customer_invoice.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("credit_note", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_credit_note_customer_id"), ["customer_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_credit_note_invoice_id"), ["invoice_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_credit_note_number"), ["number"], unique=True)

    op.create_table(
        "customer_payment",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("state_version", sa.Integer(), nullable=False),
        sa.Column("number", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column("customer_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("invoice_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("amount_cents", sa.Integer(), nullable=False),
        sa.Column("posting_date", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
        sa.Column("journal_entry_id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customer.id"],
        ),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["customer_invoice.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("customer_payment", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_customer_payment_customer_id"), ["customer_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_customer_payment_invoice_id"), ["invoice_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_customer_payment_number"), ["number"], unique=True)

    op.create_table(
        "supplier_payment",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("state_version", sa.Integer(), nullable=False),
        sa.Column("number", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.Column("supplier_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("invoice_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("amount_cents", sa.Integer(), nullable=False),
        sa.Column("posting_date", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
        sa.Column("journal_entry_id", sqlmodel.sql.sqltypes.AutoString(length=26), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["supplier_invoice.id"],
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["supplier.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("supplier_payment", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_supplier_payment_invoice_id"), ["invoice_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_supplier_payment_number"), ["number"], unique=True)
        batch_op.create_index(
            batch_op.f("ix_supplier_payment_supplier_id"), ["supplier_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("supplier_payment", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_supplier_payment_supplier_id"))
        batch_op.drop_index(batch_op.f("ix_supplier_payment_number"))
        batch_op.drop_index(batch_op.f("ix_supplier_payment_invoice_id"))

    op.drop_table("supplier_payment")
    with op.batch_alter_table("customer_payment", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_customer_payment_number"))
        batch_op.drop_index(batch_op.f("ix_customer_payment_invoice_id"))
        batch_op.drop_index(batch_op.f("ix_customer_payment_customer_id"))

    op.drop_table("customer_payment")
    with op.batch_alter_table("credit_note", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_credit_note_number"))
        batch_op.drop_index(batch_op.f("ix_credit_note_invoice_id"))
        batch_op.drop_index(batch_op.f("ix_credit_note_customer_id"))

    op.drop_table("credit_note")
    with op.batch_alter_table("supplier_invoice", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_supplier_invoice_supplier_id"))
        batch_op.drop_index(batch_op.f("ix_supplier_invoice_po_id"))
        batch_op.drop_index(batch_op.f("ix_supplier_invoice_number"))

    op.drop_table("supplier_invoice")
    with op.batch_alter_table("shipment", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_shipment_so_id"))
        batch_op.drop_index(batch_op.f("ix_shipment_number"))

    op.drop_table("shipment")
    with op.batch_alter_table("sales_order_line", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sales_order_line_so_id"))

    op.drop_table("sales_order_line")
    with op.batch_alter_table("purchase_order_line", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_purchase_order_line_po_id"))

    op.drop_table("purchase_order_line")
    with op.batch_alter_table("journal_line", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_journal_line_entry_id"))
        batch_op.drop_index(batch_op.f("ix_journal_line_account_id"))
        batch_op.drop_index(batch_op.f("ix_journal_line_account_code"))

    op.drop_table("journal_line")
    with op.batch_alter_table("goods_receipt", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_goods_receipt_po_id"))
        batch_op.drop_index(batch_op.f("ix_goods_receipt_number"))

    op.drop_table("goods_receipt")
    with op.batch_alter_table("customer_invoice", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_customer_invoice_so_id"))
        batch_op.drop_index(batch_op.f("ix_customer_invoice_number"))
        batch_op.drop_index(batch_op.f("ix_customer_invoice_customer_id"))

    op.drop_table("customer_invoice")
    with op.batch_alter_table("sales_order", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sales_order_status"))
        batch_op.drop_index(batch_op.f("ix_sales_order_number"))
        batch_op.drop_index(batch_op.f("ix_sales_order_customer_id"))

    op.drop_table("sales_order")
    with op.batch_alter_table("purchase_order", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_purchase_order_supplier_id"))
        batch_op.drop_index(batch_op.f("ix_purchase_order_status"))
        batch_op.drop_index(batch_op.f("ix_purchase_order_number"))

    op.drop_table("purchase_order")
    with op.batch_alter_table("journal_entry", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_journal_entry_source_id"))
        batch_op.drop_index(batch_op.f("ix_journal_entry_period_id"))
        batch_op.drop_index(batch_op.f("ix_journal_entry_period_code"))
        batch_op.drop_index(batch_op.f("ix_journal_entry_number"))

    op.drop_table("journal_entry")
    with op.batch_alter_table("supplier", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_supplier_code"))

    op.drop_table("supplier")
    op.drop_table("server_key")
    with op.batch_alter_table("receipt", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_receipt_tool_name"))
        batch_op.drop_index(batch_op.f("ix_receipt_document_id"))
        batch_op.drop_index(batch_op.f("ix_receipt_actor_id"))

    op.drop_table("receipt")
    with op.batch_alter_table("policy_version", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_policy_version_version"))

    op.drop_table("policy_version")
    with op.batch_alter_table("open_item", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_open_item_source_doc_id"))
        batch_op.drop_index(batch_op.f("ix_open_item_party_id"))
        batch_op.drop_index(batch_op.f("ix_open_item_kind"))

    op.drop_table("open_item")
    with op.batch_alter_table("item", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_item_sku"))

    op.drop_table("item")
    op.drop_table("idempotency_record")
    with op.batch_alter_table("fiscal_period", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_fiscal_period_code"))

    op.drop_table("fiscal_period")
    with op.batch_alter_table("event", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_event_type"))
        batch_op.drop_index(batch_op.f("ix_event_document_id"))

    op.drop_table("event")
    op.drop_table("document_sequence")
    with op.batch_alter_table("customer", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_customer_code"))

    op.drop_table("customer")
    with op.batch_alter_table("approval_request", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_approval_request_status"))
        batch_op.drop_index(batch_op.f("ix_approval_request_document_type"))
        batch_op.drop_index(batch_op.f("ix_approval_request_document_id"))

    op.drop_table("approval_request")
    with op.batch_alter_table("api_token", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_api_token_token_hash"))
        batch_op.drop_index(batch_op.f("ix_api_token_subject"))

    op.drop_table("api_token")
    with op.batch_alter_table("account", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_account_code"))

    op.drop_table("account")
    # ### end Alembic commands ###
